### ISSUE TITLE
Web app is calling rpc wich make no sense

### ISSUE THREAD

**Issue by Tocard** [NibiruChain/website-help#1]
I wanted to investigate why my adress are not on leaderboard, but I found something else on https://app.nibiru.fi/leaderboard

If you enable dev console, you will see rpc call and query.

for exemple

```json
{
    "data": {
        "markPriceCandles": [
            {
                "close": 25662,
                "periodStartTs": "2023-09-07T00:00:00Z"
            },
            {
                "close": 25662.250024,
                "periodStartTs": "2023-09-08T00:00:00Z"
            },
            {
                "close": 25662.250024,
                "periodStartTs": "2023-09-09T00:00:00Z"
            },
            {
                "close": 25662.250024,
                "periodStartTs": "2023-09-10T00:00:00Z"
            },
            {
                "close": 25667.250312,
                "periodStartTs": "2023-09-11T00:00:00Z"
            },
            {
                "close": 25662.250095,
                "periodStartTs": "2023-09-12T00:00:00Z"
            },
            {
                "close": 25662.251885,
                "periodStartTs": "2023-09-13T00:00:00Z"
            },
            {
                "close": 25662.022495,
                "periodStartTs": "2023-09-14T00:00:00Z"
            }
        ]
    }
}
```

wich has nothing to do here

![image](https://github.com/NibiruChain/website-help/assets/6951742/b3bf5808-468c-45a2-867b-344c2113966e)
And 300+ request in less than 3 minutes, this is a lot.

**Comment by cgilbe27** [comment]
Hello, this query is not from the RPC but rather from the heart monitor we have that keeps track of blockchain -> off chain

The queries you are seeing are in relation to the trading view chart on our perps page

**Comment by Tocard** [comment]
Yep, but I'm only seeing leaderboard, if every people who open the site is querying this, it will burst your rpc or proxy for nothing.

Just an advice to avoid load traffic ;)
