### ISSUE TITLE
Uninteractive Currency Changer on Swap Page when it's empty

### ISSUE THREAD

**Issue by keyboord01** [NibiruChain/website-help#10]
#### Which browser and device are you using?
    Chrome

#### What wallet are you using?
- [x] Keplr
- [ ] Leap
- [ ] Cosomostation
- [ ] Leap Cosmos Metamask
- [ ] Unable to connect

#### What's your Twitter handle?
@keyyyyripto

#### What's your Nibi address?
nibi1kacx5xj9q2ayxpz939a37phhnk7xa506rklph5

#### Would you be able to provide screenshots of the issue you're encountering?
yes

![CleanShot 2024-02-16 at 21 39 35@2x](https://github.com/NibiruChain/website-help/assets/45427966/5658ceb1-897c-46e7-9af0-1256cf886e3f)

## Review Checklist
- [x] I have provided the type of browser and device
- [x] I have provided the wallet extension used
- [x] I have provided my twitter handle
- [x] I have provided my nibi wallet address
- [ ] I have reviewed previous existing airdrop issues
- [x] I have reviewed airdrops FAQ

**Comment by cgilbe27** [comment]
Hello, this functionality is not currently supported, and is unrelated to the airdrops
