### ISSUE TITLE
[Aidrops]:  Testnet claiming issue

### ISSUE THREAD

**Issue by Shalexo** [NibiruChain/website-help#11]
#### What wallet are you using?
- [ ] Keplr
- [ ] Leap <<<<---------- this one
- [ ] Cosomostation
- [ ] Leap Cosmos Metamask
- [ ] Unable to connect

#### What's your Twitter handle?
Shalexo

#### What's your Nibi address?
nibi1qn8705l5466ln0lwrr63n7xzrk04hkja43257r

#### Would you be able to provide screenshots of the issue you're encountering?
i cant claim the NIBI i have in testnet1 for quite a while. now there is 58 the claim. usually they claimed to testnet2 (they appeared there after claiming try on testnet1) but now not anymore and always i get error message on testnet1 : Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: no validator distribution info [cosmos/cosmos-sdk@v0.47.5/baseapp/baseapp.go:802] With gas wanted: '18446744073709551615' and gas used: '29755' : unknown request   |  and also "account reached limit" on fauct on testnet1

## Review Checklist
- [ ] I have provided the type of browser and device: PC and Brave browser (Chrome engine)
- [ ] I have provided the wallet extension used: Leap
- [ ] I have provided my twitter handle: Shalexo
- [ ] I have provided my nibi wallet address: nibi1qn8705l5466ln0lwrr63n7xzrk04hkja43257r
- [ ] I have reviewed previous existing airdrop issues: yes
- [ ] I have reviewed airdrops FAQ: yes

**Comment by cgilbe27** [comment]
Hello, can you confirm if this is still an issue?
I would also recommend trying on mainnet as testnet is not as stable

**Comment by cgilbe27** [comment]
Closing this ticket, feel free to reopen if you still need help
