### ISSUE TITLE
[Aidrops]: Nibiru Airdrop Account Verified Problem

### ISSUE THREAD

**Issue by ayumiindra** [NibiruChain/website-help#13]
#### Which browser and device are you using?
    Using Chrome browser and Laptop

#### What wallet are you using?
- [✔ ] Keplr
- [ ] Leap
- [ ] Cosomostation
- [ ] Leap Cosmos Metamask
- [ ] Unable to connect

#### What's your Twitter handle?
@021Ayumi46632

#### What's your Nibi address?
nibi1squmxqzwnjr0ajvly7lu7h7w4gcnqsrwgkgp4r

#### Would you be able to provide screenshots of the issue you're encountering?
![image](https://github.com/NibiruChain/website-help/assets/165945325/99cfea56-132d-4f5a-9d00-a35525b7e437)

Hello Nibiru Team, I apologize in advance for my oversight. My account remains unconfirmed despite having followed all the rules; it turns out there was an issue with the Discord account needing to be labeled as 'seemingly human' and 'likely human.' As far as I recall, the Discord account was already labeled as 'seemingly human' and 'likely human,' but upon rechecking, the 'likely human' status was missing. Now, both 'likely human' and 'seemingly human' statuses are in place, but it's too late for confirmation. Would Nibiru be willing to assist? I am highly enthusiastic about this project; your assistance would be greatly appreciated. Thank you very much

## Review Checklist
- [ ✔] I have provided the type of browser and device
- [✔ ] I have provided the wallet extension used
- [ ✔] I have provided my twitter handle
- [✔ ] I have provided my nibi wallet address
- [ ✔] I have reviewed previous existing airdrop issues
- [ ✔] I have reviewed airdrops FAQ

**Comment by cgilbe27** [comment]
Airdrop claiming is over
