### ISSUE TITLE
Not work button "claiming" on Stake

### ISSUE THREAD

**Issue by dmk650** [NibiruChain/website-help#15]
Hi, 
The "application" button does not work for almost 2 weeks on [Stake](https://app.nibiru.fi/stake)
![not work claiming 05 06 2024](https://github.com/NibiruChain/website-help/assets/171869369/c1883353-1892-44e6-a3bb-1b714bdfa3d3)

Wallet conect Leap Cosmos MetaMask
![Wallet conect Leap Cosmos MetaMask](https://github.com/NibiruChain/website-help/assets/171869369/586b4e92-b87d-4ee4-943a-4ad76a9f8e63)

Please help!

**Comment by dmk650** [comment]
![Uploading error claming.JPG…]()

**Comment by cgilbe27** [comment]
Hello, we are unable to duplicate your issue, can you provide the browser you're using?

A screen recording would also be helpful

**Comment by cgilbe27** [comment]
Closing this issue, if you still need help, feel free to reopen the issue
