### ISSUE TITLE
Address does not show up on leaderboard

### ISSUE THREAD

**Issue by Tocard** [NibiruChain/website-help#2]
![image](https://github.com/NibiruChain/website-help/assets/6951742/67cf80b5-12c3-40a5-9931-70f2182652e7)

with adresse : nibi1cr26vwt8mzgy5v666573lv50rrj56348xxga9s

**Comment by cgilbe27** [comment]
Have you opened and close any positions since the start of phase 4?

Or do you currently have any open positions?

**Comment by Tocard** [comment]
> Have you opened and close any positions since the start of phase 4?
> 
> Or do you currently have any open positions?

Opened, closed many times, currently 2 open. was able to see myself yesterday (rank 4xx, -1%), not anymore

**Comment by cgilbe27** [comment]
It's possible you are no longer in the top 1000 which is why it doesn't show

However, you should still be able to search for that address

**Comment by Tocard** [comment]
> It's possible you are no longer in the top 1000 which is why it doesn't show
> 
> However, you should still be able to search for that address

well, nop I cannot anymore
