### ISSUE TITLE
Nibiru drop

### ISSUE THREAD

**Issue by IhorBielyk** [NibiruChain/website-help#5]
good afternoon, I participated in the Nibiru testnet, I had a node, but my wallet is not in the list, can this be somehow fixed? I also filled out the glim

my nibiru adress wallet nibi1s3jmmv59kdq8jd5wm8dlhg5sk4ysp0rvqxr8kk

THanks

**Comment by Mumtaz268** [comment]
Same issue here 

nibi1kfyddmgy3hxn6tkkzjdawqx0kcwwgd5g9kh5nz

**Comment by IhorBielyk** [comment]
What did you mean?

Сб, 10.02.2024 в 16:45, Mumtaz268 ***@***.***>:

**Comment by cgilbe27** [comment]
Hello, please reach out to our support team, this is not something we can fix on the frontend

**Comment by Mumtaz268** [comment]
Hello,
I have completed all ITN tasks filled form also but didn't find my address in excel sheet and search in NIBIRU explorer kindly check and fix my issue. Thanks

nibi1kfyddmgy3hxn6tkkzjdawqx0kcwwgd5g9kh5nz
![Nibiru ITN 4 Gealum tasks](https://github.com/NibiruChain/website-help/assets/5641205/4ee3667d-686d-45d8-9c0e-cdea200a2aba)
