### ISSUE TITLE
Clarification on testnet and reward

### ISSUE THREAD

**Issue by Malinp788** [NibiruChain/website-help#6]
Hello. I participated in the testnet but didn't get the award. My validator was in active enrollment (moniker monika address nibivaloper147yrlk479fkzlh9knc63ry479kz7a48e4f02j9
), installed pricefinder nibi1nzfrnltqgmpxw9m2nm0d969kj2qj0mkya80fsl6 and completed all tasks.  The wallet address is nibi147yrlk479fkzlh9knc63ry479kz7a48eujp3xc. Here's my gleam https://gleam.io/yW6Ho/nibiru-incentivized-testnet-registration. I tried really hard, please check it out, maybe I can get my award?

![aktivniy-validator](https://github.com/NibiruChain/website-help/assets/131196232/f0d01a96-9fa5-4f1f-b7c5-18469af59a69)
![gleam](https://github.com/NibiruChain/website-help/assets/131196232/c202303d-79c9-47bf-abd5-98738ff00386)
![skreen](https://github.com/NibiruChain/website-help/assets/131196232/6331abe2-ef5c-4b08-aac3-742c3c9e991f)

**Comment by bocin33** [comment]
I've pasted it but it always suddenly disappears. Why bro??

This my address
nibi1t044ngmlp3p5zlhks2cv4szdpw3sv03lkkdv6c

**Comment by cgilbe27** [comment]
Hello, itn-4 is over and has been for a while, this is not something we can help with for the frontend
