### ISSUE TITLE
Feature Request: Implement Dark Mode for Documentation

### ISSUE THREAD

**Issue by eminmtas** [NibiruChain/website-help#8]
The [current website](https://nibiru.fi/) features a dark mode, but the [documentation site](https://nibiru.fi/docs/) lacks this functionality. It would be great if you could implement a dark mode for the documentation website, as reading in light mode can be straining. Consider adding a toggle button in the top-right corner of the website for users to switch between light and dark modes.

I have a Chrome browser extension called Dark Reader installed. I tested the website with dark mode, and it looks fantastic, except for the scroll section. Please take a look: 

**Before:**
![image](https://github.com/NibiruChain/website-help/assets/44838743/fb66978d-9e33-481b-b08b-5ef2ec40c28d)

**After:**
![image](https://github.com/NibiruChain/website-help/assets/44838743/62a86b4e-d057-4144-b78b-f4377a86d6b1)

**Comment by eminmtas** [comment]
You guys are really busy rn, I know that. Sorry to mention, could you please check it? Thanks :)
@k-yang @Unique-Divine

**Comment by Unique-Divine** [comment]
Took a while to get to this, but it was completed a few weeks ago
